attributes:
  - source
  - location_id
  - city
  - state
  - country
  - latitude
  - longitude
  - time_zone
  - elevation
  - local_time_zone
  - dhi
  - dni
  - ghi
  - dew_points
  - dhi_units
  - dni_units
  - ghi_units
  - solar_zenith_angle_units
  - temperature_units
  - pressure_units
  - relative_humidity_units
  - precipitable_water_units
  - wind_direction_units
  - wind_speed
  - cloud_type_-15
  - cloud_type_0
  - cloud_type_1
  - cloud_type_2
  - cloud_type_3
  - cloud_type_4
  - cloud_type_5
  - cloud_type_6
  - cloud_type_7
  - cloud_type_8
  - cloud_type_9
  - cloud_type_10
  - cloud_type_11
  - cloud_type_12
  - fill_flag_0
  - fill_flag_1
  - fill_flag_2
  - fill_flag_3
  - fill_flag_4
  - fill_flag_5
  - surface_albedo_units
  - version
