file_locations:
  data_path: "../data/"
  data_path_usc: "../data/us_census/"
  data_file_usc: "2020_Gaz_zcta_national.txt"
  data_file_zips: "zip_codes.txt"
  db_path: "../data/db/"
  db_file: "tulsa-ok.db"
  db_table1: "geo_zipcodes"
  db_table2: "nsrdb.db"
  db_file_gzc: "geo_zipcodes.db"
  db_file_nsr: "nsrdb.db"
url:
  url_string: f'https://developer.nrel.gov/api/solar/nsrdb_psm3_download.csv?wkt=POINT({zip_codes[zip_code]["lon"]}%20{zip_codes[zip_code]["lat"]})&names={year}&leap_day={vars["leap_year"]}&interval={vars["interval"]}&utc={vars["utc"]}&full_name={vars["name"]}&email={vars["email"]}&affiliation={vars["affiliation"]}&mailing_list={vars["mailing_list"]}&reason={vars["use"]}&api_key={vars["key"]}&attributes={vars["attrs"]}'
url_variables:
  affiliation: University+of+Michigan
  attrs: ""
  email: gamyers@umich.edu
  interval: "60"
  key: zlLqGig0zfwIx8SJxEDaORdw4OiTv8ByHNqGhdjA
  lat: 36.0
  leap_year: "true"
  lon: -96.0
  mailing_list: "true"
  name: Gregory+Myers
  use: UMSI+Capstone+Project
  utc: "false"
  year: ""
request_years:
  - 2020
  - 2019
  - 2018
  - 2017
  - 2016
  - 2015
time_index:
  true: 1
  false: 0
num_rows: 
  - 99999